#!/usr/bin/env python3

import sys

name = 'Claudio'
color = 'Verde'
activity = 'Nadar'
animal = 'Gato'
print('My name is:', name)
print('My favorite color is:', color)
print('My favorite activity is:', activity)
print('My favorite animal is:', animal)



